# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

locale: "es"
title: "Copa América Brasil 2019"
email: "s6.bita@gmail.com"
description: "Todos los partidos de la Copa América Brasil 2019 online, en idioma ruso."

url: "https://6bita.github.io/0cc3"
baseurl: "/"
repository: "6bita/0cc3"

logo: "/assets/images/logo.png"

comments:
  provider: "disqus"
  disqus:
    shortname: "copa-america-brasil-2019"

atom_feed:
  path: "/feed.xml"
  
google_site_verification: "iEpyftl8vztFloxfazmXpcTYR8qaoj_M1FMNN9_tmwQ"
bing_site_verification: "192EA88F6C4D2A268FEFC9AB5A74172E"
yandex_site_verification: "f6b8546795302cc1"

twitter_username: BitaSci
github_username: 6bita
minimal_mistakes_skin: default


search: true

social:
  type:  "Person" # Person or Organization (defaults to Person)
  name:  "Sci Bita" # If the user or organization name differs from the site's name
  
  links:
   - https://6bita.github.io
   - https://twitter.com/BitaSci
   - https://www.youtube.com/channel/UCnorB92qbzU11pZC0qd7J6Q
   
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "UA-142981128-1"
    anonymize_ip: false # default

# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache

author:
  name   : "Sci Bita"
  avatar : "/assets/images/bio-photo.jpg"
  bio    : "SQuad: Club Atlético Peñarol"
  links:
    - label: "Website"
      icon: "fas fa-fw fa-link"
      url: "https://6bita.github.io"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BitaSci"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://6bita.github.io"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/channel/UCnorB92qbzU11pZC0qd7J6Q"

footer:
  links:
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/BitaSci"
    - label: "GitHub"
      icon: "fab fa-fw fa-github-square"
      url: "https://6bita.github.io"
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube-square"
      url: "https://www.youtube.com/channel/UCnorB92qbzU11pZC0qd7J6Q"

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true

category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
